sudo: required
language: go

go:
  - 1.4
  - 1.5
  - 1.6

services:
  - docker

script:
  - go vet -x ./compose
  - golint ./compose
  - gotestcover -coverprofile="cover.out" -race -covermode="count" ./compose
  - goveralls -coverprofile="cover.out"

after_failure:
  - docker logs ms
  - docker logs pg